run:
  timeout: 5m
issues:
  fix: true
linters:
  enable-all: true
  disable:
  - gochecknoglobals
  - funlen
  - testpackage
  - goerr113
  - exhaustivestruct
  # https://github.com/tomarrell/wrapcheck/issues/8
  - wrapcheck