apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-sync-redis
  labels:
    app: file-sync-redis
spec:
  selector:
    matchLabels:
      app: file-sync-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: file-sync-redis
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      containers:
      - name: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        image: docker-hub-proxy.alldigitalads.com/library/redis:5.0.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: file-sync-redis
  labels:
    app: file-sync-redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    protocol: TCP
  selector:
    app: file-sync-redis
