version: '3'

services:
  file-sync1:
    build:
      context: .
    command:
    - /app/file-sync
    - -sync.address=file-sync2:9335
    ports:
    - 19336:9336
  file-sync2:
    build:
      context: .
    command:
    - /app/file-sync
    - -sync.address=file-sync1:9335
    ports:
    - 29336:9336
      