version: '3'

services:
  redis:
    image: redis:alpine
  file-sync1:
    build:
      context: .
    command:
    - /app/file-sync
    - -sync.address=file-sync2:9335
    - -dir.src=/tmp
    - -redis.enabled
    - -redis.address=redis:6379
    ports:
    - 19336:9336
  file-sync2:
    build:
      context: .
    command:
    - /app/file-sync
    - -sync.address=file-sync1:9335
      