apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        revision: {{ .Release.Revision | quote }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9334"
    spec:
      tolerations:
{{ if .Values.tolerations }}
{{ toYaml .Values.tolerations | indent 6 }}
{{ end }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: {{ .Release.Name }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Release.Name }}
            topologyKey: kubernetes.io/hostname
      securityContext:
        runAsUser: {{ .Values.userUID }}
        runAsGroup: {{ .Values.userUID }}
        fsGroup: {{ .Values.userUID }}
      volumes:
      - name: certs
        configMap:
          name: {{ .Release.Name }}-certs
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.claimName }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image }}
        env:
{{ if .Values.env }}
{{ toYaml .Values.env | indent 8 }}
{{ end }}
        args:
        {{ include "args" . | nindent 8 }}
        - -redis.executeQueue=false
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: 9336
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 9336
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - mountPath: /certs
          name: certs
        - mountPath: /app/data
          name: data
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9336
    targetPort: 9336
    protocol: TCP
  selector:
    app: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-external
  labels:
    app: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 9335
    targetPort: 9335
    protocol: TCP
  selector:
    app: {{ .Release.Name }}