apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-worker
        revision: {{ .Release.Revision | quote }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9334"
    spec:
      tolerations:
{{ if .Values.tolerations }}
{{ toYaml .Values.tolerations | indent 6 }}
{{ end }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: {{ .Release.Name }}-worker
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Release.Name }}-worker
            topologyKey: kubernetes.io/hostname
      securityContext:
        runAsUser: {{ .Values.userUID }}
        runAsGroup: {{ .Values.userUID }}
        fsGroup: {{ .Values.userUID }}
      volumes:
      - name: certs
        configMap:
          name: {{ .Release.Name }}-certs
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.claimName }}
      containers:
      - name: {{ .Release.Name }}-worker
        image: {{ .Values.image }}
        env:
{{ if .Values.env }}
{{ toYaml .Values.env | indent 8 }}
{{ end }}
        args:
        {{ include "args" . | nindent 8 }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: 9336
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 9336
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - mountPath: /certs
          name: certs
        - mountPath: /app/data
          name: data