image: paskalmaksim/file-sync:v0.2.2
imagePullPolicy: IfNotPresent

dataVolume:
  ## If false, use emptyDir
  enabled: false

  spec:
    persistentVolumeClaim:
      claimName: pvc-data

replicas: 2

userUID: 82

env: []
tolerations: []

resources:
  requests:
    cpu: 100m  
    memory: 100Mi

redis:
  create: true
  endpoint: "{{ .Release.Name }}-redis:6380"
  password: ""
  useTLS: false
  useTLSInsecure: false

sync:
  # address to sync files
  address: 127.0.0.1:19335

# test certificates - please generate new certificate for production usage
# make initSSL
certs:
  CA.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDYzCCAkugAwIBAgIBATANBgkqhkiG9w0BAQsFADBCMQswCQYDVQQGEwJVUzES
    MBAGA1UEChMJZmlsZS1zeW5jMQswCQYDVQQLEwJDQTESMBAGA1UEAxMJZmlsZS1z
    eW5jMB4XDTIxMTAyOTA2NDEyM1oXDTMwMDExNTA2NDEzM1owQjELMAkGA1UEBhMC
    VVMxEjAQBgNVBAoTCWZpbGUtc3luYzELMAkGA1UECxMCQ0ExEjAQBgNVBAMTCWZp
    bGUtc3luYzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMJmXWY4fYqJ
    Cm3JAcyh1nPsVY8ecps/t0mp/l39jfyKUZPq2xKAQ4JtAbmyrSsUiSy8xQR0zH/8
    oonmJlimuIBSYla0oJecd7poqUG+Vx5cqrkhS8RGvU01LySt4+c8NMONJHXUBIkT
    pg8v1l5cSxqFR57S4tQ/gmRpUMLA1Z0ERIXTrC5/YJ8zFsddCaDykcXBFiMAv9JQ
    HKYcVJX1yChymT8ducDWHwO3L/EcoR1fkcNCjWJkwdE/yq362k1BhT48hoUP5Nqp
    WY4Wh0lqXird9ffftZFmhnqxKwu3Q0hJ96lQIZ/6qRGxJIDf57+m0Q2VdQ3dETh3
    PdOHt058f7MCAwEAAaNkMGIwDgYDVR0PAQH/BAQDAgEGMB0GA1UdJQQWMBQGCCsG
    AQUFBwMBBggrBgEFBQcDAjASBgNVHRMBAf8ECDAGAQH/AgECMB0GA1UdDgQWBBTk
    5FQjORsXDQl73a3+fXBXyWzkIjANBgkqhkiG9w0BAQsFAAOCAQEAEq9BiAnYMCsO
    19KrZzGB5Zl3dhNlHeXS54eRv8saK5RrybJVdOqy9hciLnyH6ML9F1fRoDfMEfbE
    RKwLDNKq288bHOvbIxK2tgWzm6LblIAuaAnTPE9jk++rEv1fSv7WimLdd4ixrVvr
    1drcdm2BJ2GimR+q/1TVYrpB8ZduLW0LiF6D2SPLad7/IZRe8lM/aDqEeEDCC2jU
    SKO+tO0qaGwq/ErP70FoHMnGPgAlwV5nRJJazEL9Ww2nekkomV5ISKvb/oEntXjJ
    WGcRZIqNKdgmzadiS+K95c3XXch1gXaJmd1DXkn/DyyYscr7tRAl5lE7avP+dyPM
    IsX3GixMVQ==
    -----END CERTIFICATE-----
  CA.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQDCZl1mOH2KiQpt
    yQHModZz7FWPHnKbP7dJqf5d/Y38ilGT6tsSgEOCbQG5sq0rFIksvMUEdMx//KKJ
    5iZYpriAUmJWtKCXnHe6aKlBvlceXKq5IUvERr1NNS8krePnPDTDjSR11ASJE6YP
    L9ZeXEsahUee0uLUP4JkaVDCwNWdBESF06wuf2CfMxbHXQmg8pHFwRYjAL/SUBym
    HFSV9cgocpk/HbnA1h8Dty/xHKEdX5HDQo1iZMHRP8qt+tpNQYU+PIaFD+TaqVmO
    FodJal4q3fX337WRZoZ6sSsLt0NISfepUCGf+qkRsSSA3+e/ptENlXUN3RE4dz3T
    h7dOfH+zAgMBAAECggEBAITFFRUzj8qGPjEtD6WLAsS5rNXKncuagLw29huLiOXq
    Mj0sMeM45uK1QHBrsAm0RNvhMU4R13myOfCk15vEgk5h9ffx9ZyWqM8PnEnije2W
    rKM0MmMjTTbmFAShHv5XCFJmm3g+DbrxSIEm0uovbrv2OywmK/V6Srv5kcbxnPNX
    PFGgzLIMorbG/DDZFVGAYgYcWq+kqUWUxrBSUz3h6k/9kYcmC1E3PRU8Dd7UezKT
    qmgcTkswvqdg+olF5b1K4PNGYyqnogA83/5evpzkLmK49flphAxhCD4C/kNtb+dL
    UQczKlALSN9Qirc8t8+ZDU8YOXx8YgY3YKJAoRSgnoECgYEA+JyWhTIFdG9dIGou
    1Hm+Dlsz+KsFbic5guOjh5TTS+fd7lNThg57PtgsUB0Q97LjFR2SCgOKlgUNjrpf
    /KBdZU0P6/hmK0jyn1NoxKwiycdh+md5WGr6zwB6GQHytHzB30yClKktbrp8pHup
    edBuc+/LLL/9VSsP+OL93esgplkCgYEAyC1WyOW6dLNfQa2Kx+AF9dALn56C4uHe
    TCE5l7LRc69mffZoUU30Ho30jQpvWcL7tBSy5syf0p7DczX+QHFExQmFDquIHS3K
    fgrq6AVytT8//mMmpDhILy2l9Nr8IZiiLHr6MvIC2QEtZXvQLBFwqQX3QaSL37n7
    18IuaU3ArOsCgYEAz+KYVr5SI1+v3pgLmq5GR1jqJ2hSfR6dj55sMsY2vUUgpdXV
    hMZ9NjqrKz5y3r0d950nbeoyK2oEQTIFa4hpMHj09Ftci5tPDf1AIRzTZiir/Cgk
    JtQl74w1jM29NkEQGHmww0CH9gxIh33EZFDu21FLcpsD6gC9NWAR6kxfm9kCgYEA
    rvszCZoHS0wg0ICq991UWHPsNTOSplFayKGifoDJpp6EsUdcGPZTlwHv6/pbK9PN
    wrT1TdtBOhOeNm/UOPDKdJLFxPUcnqUQhO12OivJAbawceaqOJMaRmNY1pk2HQgX
    e1pkq3PyGU92J2f7qQn1uUqFwNPdkUw6YXhUqahV7NECgYEAsVnvrycrcfCOShPS
    4z8ln/w9csJeHxNylsCOko/iQGgdKRlmEp1+V41TbUv9yV0OdWDHKcUdyl0OaZLa
    TI/55zWMcgXNxyc4inu51kqbGpaW8q5jY58rFMw/fui9e0vIWv6S5Gqk+naIh6yG
    XdfSTbeKNSiElTT6PNecrsJltL4=
    -----END PRIVATE KEY-----
